### PR TITLE
Fixed fund_sources_controller.rb

### PR DESCRIPTION
**Pull request by mrtass**
modified:   app/controllers/private/fund_sources_controller.rb
modified:   Gemfile.lock

### CODE REVIEW

**Comment by muhammednagy** [comment]
why the Gemfile.lock edits?

**Comment by mrtass** [comment]
as it's defining gon (5.2.3)
test worked with gon (5.2.0)

**Comment by muhammednagy** [comment]
but i don’t see gon updates

**Comment by mrtass** [comment]
in gemfile.lock i see 2 versions 5.2.3
gon (5.2.3)
      actionpack (>= 2.3.0)
      json
      multi_json
      request_store (>= 1.0.5)

**Comment by mrtass** [comment]
this is the error i get when leaving GON 5.2.3
production.log

I, [2018-02-15T14:37:26.182735 #8566]  INFO -- : Started GET "/funds" for 178.135.80.133 at 2018-02-15 14:37:26 +0300
I, [2018-02-15T14:37:26.189616 #8566]  INFO -- : Processing by Private::FundsController#index as HTML
I, [2018-02-15T14:37:26.203629 #8566]  INFO -- : Completed 500 Internal Server Error in 14ms
F, [2018-02-15T14:37:26.205000 #8566] FATAL -- :
RuntimeError (You can't use Gon public methods for storing data):
  app/controllers/application_controller.rb:204:in `set_gon'
  lib/middleware/security.rb:11:in `call'

**Pull request merged**
